Optimize win and linux gitlab builds

diff --git a/Dockerfile-trusty b/Dockerfile-trusty
--- a/Dockerfile-trusty
+++ b/Dockerfile-trusty
@@ -23,20 +23,22 @@ ENV BASEPREFIX=$PROJECTDIR/depends
 ENV DISTDIR=/opt/blocknetdx/dist
 ENV HOST=x86_64-pc-linux-gnu
 
-# Copy source files
-#RUN mkdir -p /opt/blocknetdx \
-#  && cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch v3.9.22 https://github.com/BlocknetDX/BlockDX.git
-COPY . /opt/blocknetdx/BlockDX/
-RUN cd $PROJECTDIR \
+# Download depends
+RUN mkdir -p $PROJECTDIR \
+  && cd $PROJECTDIR \
   && wget -nv https://s3.amazonaws.com/blockdxbuilds/devbuilds/depends-3.9.32-dev-trusty.tar.gz \
-  && [ "$(printf '509741f256bac5431e5d73bb85826af45e4e5d40490735c11fce1668387b62dc depends-3.9.32-dev-trusty.tar.gz' | sha256sum -c)" = "depends-3.9.32-dev-trusty.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1) \
-  && rm -r $BASEPREFIX \
-  && tar xzvf depends-3.9.32-dev-trusty.tar.gz
+  && [ "$(printf '509741f256bac5431e5d73bb85826af45e4e5d40490735c11fce1668387b62dc depends-3.9.32-dev-trusty.tar.gz' | sha256sum -c)" = "depends-3.9.32-dev-trusty.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+
+# Copy source files
+#RUN cd /opt/blocknetdx \
+#  && git clone --depth 1 --branch v3.9.32 https://github.com/BlocknetDX/BlockDX.git
+COPY . $PROJECTDIR/
 
 # Build source
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
+  && rm -r $BASEPREFIX \
+  && tar xzvf depends-3.9.32-dev-trusty.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure --with-gui=qt5 --enable-debug --prefix=/ \
diff --git a/Dockerfile-win b/Dockerfile-win
--- a/Dockerfile-win
+++ b/Dockerfile-win
@@ -29,20 +29,22 @@ ENV BASEPREFIX=$PROJECTDIR/depends
 ENV DISTDIR=/opt/blocknetdx/dist
 ENV HOST=x86_64-w64-mingw32
 
-# Copy source files
-#RUN mkdir -p /opt/blocknetdx \
-#  && cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch v3.9.22 https://github.com/BlocknetDX/BlockDX.git
-COPY . /opt/blocknetdx/BlockDX/
-RUN cd $PROJECTDIR \
+# Download depends
+RUN mkdir -p $PROJECTDIR \
+  && cd $PROJECTDIR \
   && wget -nv https://s3.amazonaws.com/blockdxbuilds/devbuilds/depends-3.9.32-dev-win.tar.gz \
-  && [ "$(printf '05c1dacb7b59cebd1448ace67562539a34b2ac98a8c42f5de4f77d5ba8f20587 depends-3.9.32-dev-win.tar.gz' | sha256sum -c)" = "depends-3.9.32-dev-win.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1) \
-  && rm -r $BASEPREFIX \
-  && tar xzvf depends-3.9.32-dev-win.tar.gz
+  && [ "$(printf '05c1dacb7b59cebd1448ace67562539a34b2ac98a8c42f5de4f77d5ba8f20587 depends-3.9.32-dev-win.tar.gz' | sha256sum -c)" = "depends-3.9.32-dev-win.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+
+# Copy source files
+#RUN cd /opt/blocknetdx \
+#  && git clone --depth 1 --branch v3.9.32 https://github.com/BlocknetDX/BlockDX.git
+COPY . $PROJECTDIR/
 
 # Build source
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
+  && rm -r $BASEPREFIX \
+  && tar xzvf depends-3.9.32-dev-win.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CXXFLAGS='-Wno-deprecated' --enable-reduce-exports --disable-bench --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --with-gui=qt5 --prefix=/ \
