Blocknet XBridge update gitlab build dependencies

diff --git a/Dockerfile-linux b/Dockerfile-linux
--- a/Dockerfile-linux
+++ b/Dockerfile-linux
@@ -32,20 +32,17 @@ ENV HOST=x86_64-pc-linux-gnu
 # Download depends
 RUN mkdir -p $PROJECTDIR \
   && cd $PROJECTDIR \
-  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v18-bionic.tar.gz \
-  && [ "$(printf '60179d28994e59db3d793daa6d4e0e76ad0ca9df8b024f4db614bd3a4acbaa56 depends-v18-bionic.tar.gz' | sha256sum -c)" = "depends-v18-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v18-lin-bionic2.tar.gz \
+  && [ "$(printf '213bcfeb7ad6cf92896398054614af46950a3ff7af972d3f5790124067f2a367 depends-v18-lin-bionic2.tar.gz' | sha256sum -c)" = "depends-v18-lin-bionic2.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
 
 # Copy source files
-#RUN cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch blocknet https://github.com/blocknetdx/bitcoin.git tmp \
-#  && mv tmp/* bitcoin/
 COPY . $PROJECTDIR/
 
 # Build source
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
   && rm -r $BASEPREFIX \
-  && tar xzvf depends-v18-bionic.tar.gz \
+  && tar xzvf depends-v18-lin-bionic2.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CC=gcc-8 CXX=g++-8 CFLAGS="-g -O0" CXXFLAGS="-g -O0" --enable-debug --prefix=/ \
diff --git a/Dockerfile-mac b/Dockerfile-mac
--- a/Dockerfile-mac
+++ b/Dockerfile-mac
@@ -34,20 +34,17 @@ ENV HOST=x86_64-apple-darwin14
 # Download depends
 RUN mkdir -p $PROJECTDIR \
   && cd $PROJECTDIR \
-  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v18-mac-bionic.tar.gz \
-  && [ "$(printf 'bebd03b6382ba3b1e3dabfa40865a7cd752902ab6600ad0bd8d9239240f152ca depends-v18-mac-bionic.tar.gz' | sha256sum -c)" = "depends-v18-mac-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v18-mac-bionic2.tar.gz \
+  && [ "$(printf 'f70b814ee72124dca43ccdef43b9748cf400e26d1110dc6f0fecb696d639162d depends-v18-mac-bionic2.tar.gz' | sha256sum -c)" = "depends-v18-mac-bionic2.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
 
 # Copy source files
-#RUN cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch blocknet https://github.com/blocknetdx/bitcoin.git tmp \
-#  && mv tmp/* bitcoin/
 COPY . $PROJECTDIR/
 
 # Build source
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
   && rm -r $BASEPREFIX \
-  && tar xzf depends-v18-mac-bionic.tar.gz \
+  && tar xzf depends-v18-mac-bionic2.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CFLAGS="-g -O0" CXXFLAGS="-g -O0" --with-gui=qt5 --enable-debug --prefix=/ \
diff --git a/Dockerfile-win b/Dockerfile-win
--- a/Dockerfile-win
+++ b/Dockerfile-win
@@ -33,20 +33,17 @@ ENV HOST=x86_64-w64-mingw32
 # Download depends
 RUN mkdir -p $PROJECTDIR \
   && cd $PROJECTDIR \
-  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v18-win-bionic.tar.gz \
-  && [ "$(printf '2541c27c8aabc19dc52582c2ed69864cbace08ba6585722d4b2a6e51632eddef depends-v18-win-bionic.tar.gz' | sha256sum -c)" = "depends-v18-win-bionic.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
+  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-v18-win-bionic2.tar.gz \
+  && [ "$(printf '1d1f239efccacefd8a396b274d8f380edeaf79ba16a5530297dd58e6f6ebd665 depends-v18-win-bionic2.tar.gz' | sha256sum -c)" = "depends-v18-win-bionic2.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1)
 
 # Copy source files
-#RUN cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch blocknet https://github.com/blocknetdx/bitcoin.git tmp \
-#  && mv tmp/* bitcoin/
 COPY . $PROJECTDIR/
 
 # Build source
 RUN mkdir -p $DISTDIR \
   && cd $PROJECTDIR \
   && rm -r $BASEPREFIX \
-  && tar xzvf depends-v18-win-bionic.tar.gz \
+  && tar xzvf depends-v18-win-bionic2.tar.gz \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CFLAGS="-g -O0" CXXFLAGS="-g -O0 -Wno-deprecated -Wa,-mbig-obj" --disable-maintainer-mode --disable-dependency-tracking --enable-debug --prefix=/ \
