3.10.6 gitlab builds

diff --git a/Dockerfile-trusty b/Dockerfile-trusty
--- a/Dockerfile-trusty
+++ b/Dockerfile-trusty
@@ -26,13 +26,13 @@ ENV HOST=x86_64-pc-linux-gnu
 # Copy source files
 #RUN mkdir -p /opt/blocknetdx \
 #  && cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch v3.9.22 https://github.com/BlocknetDX/BlockDX.git
+#  && git clone --depth 1 --branch v3.10.6 https://github.com/BlocknetDX/BlockDX.git
 COPY . /opt/blocknetdx/BlockDX/
 RUN cd $PROJECTDIR \
-  && wget -nv https://s3.amazonaws.com/blockdxbuilds/devbuilds/depends-3.9.32-dev-trusty.tar.gz \
-  && [ "$(printf '509741f256bac5431e5d73bb85826af45e4e5d40490735c11fce1668387b62dc depends-3.9.32-dev-trusty.tar.gz' | sha256sum -c)" = "depends-3.9.32-dev-trusty.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1) \
+  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-3.10.6-dev-trusty.tar.gz \
+  && [ "$(printf 'c48b488097bd5f9b70a83f95c3226bb3d10fef0aec3b462ba69bfbf1cdb0cf0b depends-3.10.6-dev-trusty.tar.gz' | sha256sum -c)" = "depends-3.10.6-dev-trusty.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1) \
   && rm -r $BASEPREFIX \
-  && tar xzvf depends-3.9.32-dev-trusty.tar.gz
+  && tar xzvf depends-3.10.6-dev-trusty.tar.gz
 
 # Build source
 RUN mkdir -p $DISTDIR \
@@ -40,6 +40,7 @@ RUN mkdir -p $DISTDIR \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure --with-gui=qt5 --enable-debug --prefix=/ \
+  && make clean \
   && echo "Building with cores: $ecores" \
   && make -j$ecores \
   && make install DESTDIR=$DISTDIR \
diff --git a/Dockerfile-win b/Dockerfile-win
--- a/Dockerfile-win
+++ b/Dockerfile-win
@@ -32,13 +32,13 @@ ENV HOST=x86_64-w64-mingw32
 # Copy source files
 #RUN mkdir -p /opt/blocknetdx \
 #  && cd /opt/blocknetdx \
-#  && git clone --depth 1 --branch v3.9.22 https://github.com/BlocknetDX/BlockDX.git
+#  && git clone --depth 1 --branch v3.10.6 https://github.com/BlocknetDX/BlockDX.git
 COPY . /opt/blocknetdx/BlockDX/
 RUN cd $PROJECTDIR \
-  && wget -nv https://s3.amazonaws.com/blockdxbuilds/devbuilds/depends-3.9.32-dev-win.tar.gz \
-  && [ "$(printf '05c1dacb7b59cebd1448ace67562539a34b2ac98a8c42f5de4f77d5ba8f20587 depends-3.9.32-dev-win.tar.gz' | sha256sum -c)" = "depends-3.9.32-dev-win.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1) \
+  && wget -nv https://s3.us-east-2.amazonaws.com/devbuilds.blocknetprotocol.com/depends/depends-3.10.6-dev-win.tar.gz \
+  && [ "$(printf 'aa2ef991c76c4c138f99905e9e81be49770573dff7a8dc33fcd2593ae3d996d8 depends-3.10.6-dev-win.tar.gz' | sha256sum -c)" = "depends-3.10.6-dev-win.tar.gz: OK" ] || $(echo "depends checksum failed"; exit 1) \
   && rm -r $BASEPREFIX \
-  && tar xzvf depends-3.9.32-dev-win.tar.gz
+  && tar xzvf depends-3.10.6-dev-win.tar.gz
 
 # Build source
 RUN mkdir -p $DISTDIR \
@@ -46,6 +46,7 @@ RUN mkdir -p $DISTDIR \
   && chmod +x ./autogen.sh; sync \
   && ./autogen.sh \
   && CONFIG_SITE=$BASEPREFIX/$HOST/share/config.site ./configure CXXFLAGS='-Wno-deprecated' --enable-reduce-exports --disable-bench --disable-ccache --disable-maintainer-mode --disable-dependency-tracking --with-gui=qt5 --prefix=/ \
+  && make clean \
   && echo "Building with cores: $ecores" \
   && make -j$ecores \
   && make install DESTDIR=$DISTDIR \
